import Image from "next/image";
import Link from "next/link";

import { Button } from "@/components/Button";
import { Container } from "@/components/Container";
import type { OverviewCard, OverviewContent, PrivatePage, RenewalContent, ServiceDetailContent } from "@/lib/private-pages";

export function PrivatePageRenderer({ page, preview = false }: { page: PrivatePage; preview?: boolean }) {
  return <><Hero page={page} preview={preview} />{page.pageType === "support_overview" ? <Overview content={page.content as OverviewContent} /> : page.pageType === "service_detail" ? <ServiceDetail page={page} content={page.content as ServiceDetailContent} /> : <Renewal page={page} content={page.content as RenewalContent} />}</>;
}

function Hero({ page, preview }: { page: PrivatePage; preview: boolean }) {
  const eyebrow = page.pageType === "support_overview" ? (page.content as OverviewContent).eyebrow : page.pageType === "service_detail" ? (page.content as ServiceDetailContent).eyebrow : (page.content as RenewalContent).eyebrow;
  const preparing = page.pageType === "service_detail" && (page.content as ServiceDetailContent).preparing;
  return <section className="relative overflow-hidden bg-[var(--color-dark)] py-20 text-white sm:py-24 lg:py-28"><div className="stars-layer" /><div className="noise-layer" /><div className="pointer-events-none absolute inset-x-0 top-0 mx-auto h-80 max-w-5xl opacity-35 blur-3xl" style={{ background: "var(--gradient-brand-diagonal)" }} /><Container className="relative"><div className="mx-auto max-w-4xl text-center">{preview ? <p className="mx-auto mb-5 w-fit rounded-full border border-amber-300/40 bg-amber-300/10 px-4 py-2 text-xs font-bold tracking-[0.16em] text-amber-100">NÁHLED KONCEPTU</p> : null}<p className="text-sm font-bold tracking-[0.18em] text-[#bba4ff]">{eyebrow}</p>{preparing ? <p className="mx-auto mt-5 w-fit rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm font-semibold">Připravujeme</p> : null}<h1 className="mt-5 text-balance text-4xl font-black leading-[1.08] tracking-tight sm:text-5xl lg:text-6xl">{page.title}</h1><p className="mx-auto mt-6 max-w-3xl text-balance text-lg leading-relaxed text-[var(--color-text-on-dark-muted)] sm:text-xl">{page.subtitle}</p></div>{page.featuredImageUrl && page.featuredImageAlt ? <div className="relative mx-auto mt-12 aspect-[16/7] max-w-5xl overflow-hidden rounded-[var(--radius-card)] border border-white/10 shadow-[var(--shadow-card)]"><Image src={page.featuredImageUrl} alt={page.featuredImageAlt} fill priority className="object-cover" sizes="(max-width: 768px) 100vw, 1024px" /></div> : null}</Container></section>;
}

function Overview({ content }: { content: OverviewContent }) {
  const cards = content.cards.filter((card) => card.active).sort((a, b) => a.sortOrder - b.sortOrder);
  return <section className="bg-[var(--color-surface-muted)] py-[var(--space-section)]"><Container><div className="grid grid-cols-1 items-stretch gap-6 md:grid-cols-2 lg:grid-cols-3">{cards.map((card) => <SupportCard key={card.id} card={card} />)}</div>{content.afterCards ? <p className="mx-auto mt-12 max-w-3xl text-center text-lg leading-relaxed text-[var(--color-text-muted)]">{content.afterCards}</p> : null}{content.finalCta.active ? <div className="mt-9 flex justify-center"><Button href={content.finalCta.url} className="px-8 py-4">{content.finalCta.label}</Button></div> : null}</Container></section>;
}

const cardStyles: Record<OverviewCard["variant"], { shell: string; muted: string; bullet: string; button: "gradient" | "outline-light" | "outline-dark" }> = {
  light: { shell: "border border-[var(--color-border-light)] bg-white text-[var(--color-text)] shadow-[var(--shadow-card)]", muted: "text-[var(--color-text-muted)]", bullet: "bg-[#eee8ff] text-[var(--color-accent-purple)]", button: "gradient" },
  gradient: { shell: "border border-white/20 bg-[linear-gradient(135deg,#2f6bff,#9b3ddb)] text-white shadow-[0_28px_70px_-25px_rgba(70,70,235,0.75)]", muted: "text-white/82", bullet: "bg-white/18 text-white", button: "outline-dark" },
  dark: { shell: "border border-white/10 bg-[linear-gradient(135deg,#10163a,#2a1b57)] text-white shadow-[var(--shadow-card)]", muted: "text-white/72", bullet: "bg-white/12 text-[#c4aeff]", button: "outline-dark" },
};

function SupportCard({ card }: { card: OverviewCard }) {
  const style = cardStyles[card.variant];
  return <article className={`flex h-full min-w-0 flex-col rounded-2xl p-6 transition duration-200 hover:-translate-y-1 hover:shadow-[var(--shadow-card-hover)] sm:p-7 ${style.shell}`}><p className="text-xs font-extrabold tracking-[0.16em] opacity-85">{card.eyebrow}</p><h2 className="mt-4 break-words text-2xl font-black leading-tight sm:text-3xl">{card.title}</h2><p className={`mt-4 leading-relaxed ${style.muted}`}>{card.description}</p><h3 className="mt-7 text-base font-extrabold">{card.benefitsHeading}</h3><ul className="mt-3 space-y-3">{card.benefits.map((benefit) => <li key={benefit} className="flex min-w-0 gap-2.5"><span aria-hidden="true" className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-[11px] font-black ${style.bullet}`}>✓</span><span className="min-w-0 break-words text-sm leading-relaxed">{benefit}</span></li>)}</ul>{card.supportingText ? <p className={`mt-6 text-sm leading-relaxed ${style.muted}`}>{card.supportingText}</p> : null}<div className="mt-auto pt-6">{card.price ? <div className="mb-5"><p className="text-3xl font-black">{card.price}</p>{card.priceNote ? <p className={`mt-1 text-sm ${style.muted}`}>{card.priceNote}</p> : null}</div> : null}<Button href={`/${card.targetSlug}`} variant={style.button} className={`w-full justify-center py-3.5 text-center focus-visible:outline-2 focus-visible:outline-offset-4 ${card.variant === "light" ? "focus-visible:outline-[var(--color-accent-purple)]" : "focus-visible:outline-white"}`}>{card.ctaLabel}</Button></div></article>;
}

function ServiceDetail({ page, content }: { page: PrivatePage; content: ServiceDetailContent }) {
  const ctaUrl = content.cta.active ? page.salesLinks[content.cta.salesLinkKey] : undefined;
  return <div className="bg-white"><Container className="py-[var(--space-section)]"><div className="mx-auto grid max-w-5xl gap-8 lg:grid-cols-[minmax(0,1.5fr)_minmax(17rem,0.8fr)]"><div className="space-y-8">{content.sections.audience ? <ContentSection title="Pro koho služba je"><BulletList items={content.audience} /></ContentSection> : null}{content.sections.benefits ? <ContentSection title="Co získáš"><BulletList items={content.benefits} /></ContentSection> : null}{content.sections.process ? <ContentSection title="Jak služba probíhá"><ol className="space-y-4">{content.process.map((step, index) => <li key={step} className="flex gap-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#eee8ff] font-black text-[var(--color-accent-purple)]">{index + 1}</span><span className="pt-1.5 leading-relaxed text-[var(--color-text-muted)]">{step}</span></li>)}</ol></ContentSection> : null}{content.sections.inclusions ? <ContentSection title="Co služba obsahuje"><BulletList items={content.inclusions} /></ContentSection> : null}{content.additionalInfo ? <p className="rounded-2xl bg-[var(--color-surface-muted)] p-6 leading-relaxed text-[var(--color-text-muted)]">{content.additionalInfo}</p> : null}</div><aside className="h-fit rounded-2xl bg-[linear-gradient(135deg,#10163a,#2a1b57)] p-7 text-white shadow-[var(--shadow-card)] lg:sticky lg:top-6">{content.sections.price && content.price ? <div><p className="text-sm font-bold uppercase tracking-[0.16em] text-white/65">Cena</p><p className="mt-2 text-4xl font-black">{content.price}</p>{content.priceNote ? <p className="mt-2 text-white/70">{content.priceNote}</p> : null}</div> : <p className="text-lg font-bold">Vyber si další krok</p>}{content.sections.cta && ctaUrl ? <div className="mt-7"><Button href={ctaUrl} target={ctaUrl.startsWith("https://") ? "_blank" : undefined} rel={ctaUrl.startsWith("https://") ? "noopener noreferrer" : undefined} className="w-full justify-center py-4 text-center">{content.cta.label}</Button>{content.buttonNote ? <p className="mt-3 text-center text-sm leading-relaxed text-white/65">{content.buttonNote}</p> : null}</div> : null}{content.contactText ? <p className="mt-6 border-t border-white/10 pt-6 text-sm leading-relaxed text-white/70">{content.contactText}</p> : null}<BackLink /></aside></div></Container></div>;
}

function Renewal({ page, content }: { page: PrivatePage; content: RenewalContent }) {
  const ctaUrl = content.cta.active ? page.salesLinks[content.cta.salesLinkKey] : undefined;
  return <section className="bg-[var(--color-surface-muted)] py-[var(--space-section)]"><Container><div className="mx-auto grid max-w-5xl gap-8 lg:grid-cols-[minmax(0,1.35fr)_minmax(18rem,0.75fr)]"><div className="space-y-8"><ContentSection title="Co pokračování obsahuje"><BulletList items={content.benefits} /></ContentSection><ContentSection title="Jak období naváže"><p className="text-lg leading-relaxed text-[var(--color-text-muted)]">{content.continuityText}</p></ContentSection>{content.contactNote ? <p className="rounded-2xl border border-[var(--color-border-light)] bg-white p-6 leading-relaxed text-[var(--color-text-muted)]">{content.contactNote}</p> : null}</div><aside className="h-fit rounded-2xl bg-white p-7 shadow-[var(--shadow-card)] lg:sticky lg:top-6"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[var(--color-accent-purple)]">Cena pokračování</p><p className="mt-3 text-4xl font-black">{content.price}</p><p className="mt-2 text-[var(--color-text-muted)]">{content.priceNote}</p>{ctaUrl ? <Button href={ctaUrl} target={ctaUrl.startsWith("https://") ? "_blank" : undefined} rel={ctaUrl.startsWith("https://") ? "noopener noreferrer" : undefined} className="mt-7 w-full justify-center py-4 text-center">{content.cta.label}</Button> : null}<BackLink dark /></aside></div></Container></section>;
}

function ContentSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-[var(--color-border-light)] bg-white p-6 shadow-[0_18px_45px_-35px_rgba(20,10,60,0.45)] sm:p-8"><h2 className="text-2xl font-black sm:text-3xl">{title}</h2><div className="mt-5">{children}</div></section>; }
function BulletList({ items }: { items: string[] }) { return <ul className="grid gap-4 sm:grid-cols-2">{items.map((item) => <li key={item} className="flex min-w-0 gap-3"><span aria-hidden="true" className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#eee8ff] text-xs font-black text-[var(--color-accent-purple)]">✓</span><span className="min-w-0 break-words leading-relaxed text-[var(--color-text-muted)]">{item}</span></li>)}</ul>; }
function BackLink({ dark = false }: { dark?: boolean }) { return <Link href="/nabidka-podpory" className={`mt-6 inline-flex min-h-11 items-center text-sm font-semibold underline underline-offset-4 transition focus-visible:outline-2 focus-visible:outline-offset-4 ${dark ? "text-[var(--color-accent-purple)] focus-visible:outline-[var(--color-accent-purple)]" : "text-white/75 hover:text-white focus-visible:outline-white"}`}>← Zpět na přehled podpory</Link>; }
